### ISSUE TITLE
Dragging map opens event

### ISSUE THREAD

**Issue by jxpsert** [openstreetmap-netherlands/openstreetmap-website#1]
When the map preview is dragged on the /events page, it opens the event once the drag is released.

I don't think that's intended behaviour?

**Comment by jxpsert** [comment]
Seems to be caused by [line 12 in event-card.tsx](https://github.com/openstreetmap-netherlands/openstreetmap-website/blob/8af00a384cc5c9a00c2d6db3cb75613a0e05608c/src/components/event/event-card.tsx#L12C22-L12C22) - the entire card is encapsulated in a ``<Link>``

Not too sure how to solve that elegantly.

**Comment by tjur0** [comment]
I have disabled the map interaction on the preview, if people want a bigger map they need to view the detail page.
