### ISSUE TITLE
Make website language all Dutch

### ISSUE THREAD

**Issue by justb4** [openstreetmap-netherlands/openstreetmap-website#8]
The wording and menus in the website is now partly Dutch, partly English. My guess is that the intention is to make the it all-Dutch, or maybe, more work, multi/bi-lingual. All Dutch for now would be fine IMHO.

A quick review of content to make Dutch:

* main/top menu and submenus
* Page names and Descriptions: Projects, Events, News, Community (ok, News/Events content is from Weekly-OSM/OSMCal, thus remains Eng.)

**Comment by tjur0** [comment]
I have translated everything (as far as i can see) to Dutch, I wanted English and Dutch however that would need more work
